# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cperson.proto\x12\x06person\" \n\rPersonRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\x0ePersonResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2N\n\rPersonService\x12=\n\nSendPerson\x12\x15.person.PersonRequest\x1a\x16.person.PersonResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'person_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PERSONREQUEST']._serialized_start=24
  _globals['_PERSONREQUEST']._serialized_end=56
  _globals['_PERSONRESPONSE']._serialized_start=58
  _globals['_PERSONRESPONSE']._serialized_end=91
  _globals['_PERSONSERVICE']._serialized_start=93
  _globals['_PERSONSERVICE']._serialized_end=171
# @@protoc_insertion_point(module_scope)
