# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63onnection.proto\x12\nconnection\"$\n\x11\x43onnectionRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"%\n\x12\x43onnectionResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2f\n\x11\x43onnectionService\x12Q\n\x0eSendConnection\x12\x1d.connection.ConnectionRequest\x1a\x1e.connection.ConnectionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'connection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CONNECTIONREQUEST']._serialized_start=32
  _globals['_CONNECTIONREQUEST']._serialized_end=68
  _globals['_CONNECTIONRESPONSE']._serialized_start=70
  _globals['_CONNECTIONRESPONSE']._serialized_end=107
  _globals['_CONNECTIONSERVICE']._serialized_start=109
  _globals['_CONNECTIONSERVICE']._serialized_end=211
# @@protoc_insertion_point(module_scope)
