---
swagger: '2.0'
info:
  version: '1.0'
  title: 'Get Person by ID API'
paths:
  /persons/{person_id}:
    get:
      tags:
      - 'Persons'
      description: 'Get a person by ID'
      parameters:
      - name: 'person_id'
        in: 'path'
        description: 'ID of the person to retrieve'
        required: true
        type: 'integer'
      responses:
        '200':
          description: 'Successful response'
          schema:
            $ref: '#/definitions/Person'
definitions:
  Person:
    type: 'object'
    properties:
      id:
        type: 'integer'
      first_name:
        type: 'string'
      last_name:
        type: 'string'
      company_name:
        type: 'string'
